### ISSUE TITLE
SNOBFIT error for initialization with nreq=1

### ISSUE THREAD

**Issue by jangerit** [scikit-quant/scikit-quant#10]
* Operating System: Ubuntu 18.04.4
* Python version: 3.8.2
* scikit-quant version used: https://github.com/scikit-quant/scikit-quant

### Description

I ran the **test03_Hartman6** test on the SNOBFIT implementation within the `test_snobfit.py` file with a number of required points per iteration of 1 and no initial points given. This causes in issue with line 331 in `snobfit.py` when calling `snob5.py`.

### What I Did
Run test03_Hartman6 with `options = optset(maxmp=1)`:

```python
    def test03_Hartman6(self):
        """Minimize Hartman6 function"""

        import SQSnobFit

        def Hartman6(x):
            import numpy, math

            a = numpy.array(
                [[10.00,  0.05,  3.00, 17.00],
                 [ 3.00, 10.00,  3.50,  8.00],
                 [17.00, 17.00,  1.70,  0.05],
                 [ 3.50,  0.10, 10.00, 10.00],
                 [ 1.70,  8.00, 17.00,  0.10],
                 [ 8.00, 14.00,  8.00, 14.00]])

            p = numpy.array(
                [[0.1312, 0.2329, 0.2348, 0.4047],
                 [0.1696, 0.4135, 0.1451, 0.8828],
                 [0.5569, 0.8307, 0.3522, 0.8732],
                 [0.0124, 0.3736, 0.2883, 0.5743],
                 [0.8283, 0.1004, 0.3047, 0.1091],
                 [0.5886, 0.9991, 0.6650, 0.0381]])

            c = numpy.array([1.0, 1.2, 3.0, 3.2])

            d = numpy.zeros((4,))
            for i in range(4):
                d[i] = sum(a[:,i]*(x - p[:,i])**2)

            return -(c.dot(numpy.exp(-d)))

        def run_Hartman6(self, initial, expected):
            self.reset()

            bounds = np.array([[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]], dtype=float)
            budget = 250
            x0 = np.array(initial)

            from SQSnobFit import optset
            options = optset(maxmp=1,verbose=True)
            config = {"bounds": bounds, "nreq": 1, "p": .5}
            result, history = SQSnobFit.minimize(Hartman6, x0, bounds, budget, config, optin=options)
            print(result)
            assert np.round(sum(result.optpar)-sum(expected), 8) == 0


      # note: results are still subtly different from the reference, but the most likeley
      # reason seems to be that the respective random number generators differ slightly
        run_Hartman6(self, [],      (0.2077,  0.14892, 0.4829,  0.2725,  0.31493, 0.66138))
        run_Hartman6(self, [0.5]*6, (0.20133, 0.1504,  0.47666, 0.27787, 0.3134,  0.65797))
```
I get the following error:
```bash
Traceback (most recent call last):
  File "test_snobfit.py", line 383, in <module>
    tester.test03_Hartman6()
  File "test_snobfit.py", line 132, in test03_Hartman6
    run_Hartman6(self, [],      (0.2077,  0.14892, 0.4829,  0.2725,  0.31493, 0.66138))
  File "test_snobfit.py", line 125, in run_Hartman6
    result, history = SQSnobFit.minimize(Hartman6, x0, bounds, budget, config, optin=options)
  File "..\python\SQSnobFit\_snobfit.py", line 206, in minimize
    config, dx)
  File "..\python\SQSnobFit\_snobfit.py", line 338, in snobfit
    request = numpy.concatenate((x5, numpy.nan*numpy.ones((nreq,1)), 5*numpy.ones((nreq,1))), 1)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

### What might cause this:
`_snob5.py` returns a one-dimensional array if nreq=1 and no initial points are given.

### Possible adjustment:
Change line 73 in `_snob5.py` from `x5 = xnew[0,:]` to `x5 = [xnew[0,:]]`

**Comment by wlav** [comment]
Fixed in repo in a slightly different way.

Thanks!
