### ISSUE TITLE
High maxfail causes error

### ISSUE THREAD

**Issue by jangerit** [scikit-quant/scikit-quant#11]
* Operating System: Ubuntu 18.04.4
* Python version: 3.8.2
* scikit-quant version used: https://github.com/scikit-quant/scikit-quant

### Description

I ran the **test03_Hartman6** test on the SNOBFIT implementation within the `test_snobfit.py` file with a high threshold for stopping, setting maxfail to high values (about >20). This causes in issue with line 354 in `snobfit.py` when calling `snobupdt.py`.

### What I Did
Run test03_Hartman6 with `options = optset(maxmp=6+6, maxfail=500)`, same with values for maxfail > 20:

```python
    def test03_Hartman6(self):
    """Minimize Hartman6 function"""

    import SQSnobFit

        def Hartman6(x):
            import numpy, math

            a = numpy.array(
                [[10.00,  0.05,  3.00, 17.00],
                 [ 3.00, 10.00,  3.50,  8.00],
                 [17.00, 17.00,  1.70,  0.05],
                 [ 3.50,  0.10, 10.00, 10.00],
                 [ 1.70,  8.00, 17.00,  0.10],
                 [ 8.00, 14.00,  8.00, 14.00]])

            p = numpy.array(
                [[0.1312, 0.2329, 0.2348, 0.4047],
                 [0.1696, 0.4135, 0.1451, 0.8828],
                 [0.5569, 0.8307, 0.3522, 0.8732],
                 [0.0124, 0.3736, 0.2883, 0.5743],
                 [0.8283, 0.1004, 0.3047, 0.1091],
                 [0.5886, 0.9991, 0.6650, 0.0381]])

            c = numpy.array([1.0, 1.2, 3.0, 3.2])

            d = numpy.zeros((4,))
            for i in range(4):
                d[i] = sum(a[:,i]*(x - p[:,i])**2)

            return -(c.dot(numpy.exp(-d)))

        def run_Hartman6(self, initial, expected, options=None):
            self.reset()

            bounds = np.array([[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]], dtype=float)
            budget = 2000
            x0 = np.array(initial)

            from SQSnobFit import optset
            if options is None:
                options = optset(maxmp=6+6, maxfail=500)
            result, history = SQSnobFit.minimize(Hartman6, x0, bounds, budget, options)

            assert np.round(sum(result.optpar)-sum(expected), 8) == 0

      # note: results are still subtly different from the reference, but the errors seem to
      # accumulate over many iterations, not produced by a single step going wrong and the
      # results here actually slightly outperform (?)
        run_Hartman6(self, [],      (0.20687, 0.14968, 0.48076, 0.27357, 0.3145,  0.66129))
        run_Hartman6(self, [0.5]*6, (0.21015, 0.12032, 0.46593, 0.27053, 0.30835, 0.66478))

      # regression: the following used to fail
        run_Hartman6(self, [],      (0.02423, 0.12107, 0.98254, 0.05482, 0.07433, 0.86491), {'maxmp' : 1})
        run_Hartman6(self, [],      (0.24101, 0.16523, 0.43633, 0.28035, 0.31964, 0.64909), {'maxmp' : 2, 'maxfail' : 10})

```
I got the following error:
```bash
Traceback (most recent call last):
  File "test_snobfit.py", line 258, in <module>
    tester.test03_Hartman6()
  File "test_snobfit.py", line 133, in test03_Hartman6
    run_Hartman6(self, [],      (0.20687, 0.14968, 0.48076, 0.27357, 0.3145,  0.66129))
  File "test_snobfit.py", line 126, in run_Hartman6
    result, history = SQSnobFit.minimize(Hartman6, x0, bounds, budget, options)
  File "..\python\SQSnobFit\_snobfit.py", line 223, in minimize
    request, xbest, fbest = snobfit(x, vals, config)
  File "..\python\SQSnobFit\_snobfit.py", line 354, in snobfit
    snobupdt(xl, xu, x, f, nsplit, small, near, d, np, t, xnew, fnew, fnan, u, v, u1, v1, dx)
  File "..\python\SQSnobFit\_snobupdt.py", line 185, in snobupdt
    xl[j] = xl0[k]
ValueError: could not broadcast input array from shape (2,1,6) into shape (6)
```

### What might cause this:
At some point in line 184 `k = find(numpy.sum(x0 == numpy.ones((nxj,1))*x[j,:], axis=1) == n)` of `_snobupt.py` k contains more than one value.

**Comment by wlav** [comment]
What is happening is that the area to fit has reduced to pretty much zero. It would be better if that condition led to convergence directly, but this is rather deep inside the snobfit code, so not easy to communicate back (in a clean way, that is). It won't show up if maxfail is set to anything sensible. :)

The same problem is in the original code, but the specific snippet has a workaround in several other places, so I put another one in (as well as a few more in subsequent places b/c next sampling fails, too, of course).
