### ISSUE TITLE
error with snobfit for univariate function (2/4)

### ISSUE THREAD

**Issue by salperinlea** [scikit-quant/scikit-quant#3]
For snobfit with one variable, the following code throws the following error:

```
import numpy as np
from skquant.opt import minimize

def f(a):
    return a[0]**2 - a[0]

bounds=np.array([[0,2]],dtype=np.float)
init=np.array([1.])
res,hist=minimize(f,init,bounds,method='snobfit')
```

```

Traceback (most recent call last):
  File "/Users/sumneralperin-lea/science_git/Tequila/examples/debug.py", line 9, in <module>
    res,hist=minimize(f,init,bounds,method='snobfit')
  File "/Users/sumneralperin-lea/git/scikit-quant/skquant/opt/__init__.py", line 54, in minimize
    return optimizer.minimize(func, x0, bounds, budget, options, **optkwds)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQSnobFit/_snobfit.py", line 223, in minimize
    request, xbest, fbest = snobfit(x, vals, config)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQSnobFit/_snobfit.py", line 374, in snobfit
    y[j], f[j,2], c, sigma[j] = snoblocf(j, x, f[:,0:2], near, dx, u, v)
IndexError: index 2 is out of bounds for axis 1 with size 2
```
(edited to fix formatting)

**Comment by wlav** [comment]
Regression test added, fixed in repo, and released on PyPI.
