### ISSUE TITLE
error in imfil with multivariate function (3/4)

### ISSUE THREAD

**Issue by salperinlea** [scikit-quant/scikit-quant#4]
Code to produce the error:

```
import numpy as np
from skquant.opt import minimize

def g(a):
    return a[0]**2 - a[0] +a[1]**3 -4*a[1]

bounds=np.array([[0,2],[-2,2]],dtype=np.float)
init=np.array([1.,0.])
res,hist=minimize(g,init,bounds,method='imfil')
```

The error:
```
Traceback (most recent call last):
  File "/Users/sumneralperin-lea/science_git/Tequila/examples/debug.py", line 16, in <module>
    res,hist=minimize(g,init,bounds,method='imfil')
  File "/Users/sumneralperin-lea/git/scikit-quant/skquant/opt/__init__.py", line 54, in minimize
    return optimizer.minimize(func, x0, bounds, budget, options, **optkwds)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQImFil/_imfil.py", line 208, in minimize
    imfil_core(z0, f_internal, budget, core_data, bounds)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQImFil/_imfil.py", line 402, in imfil_core
    error_check('first_eval', funs, options, iff)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQImFil/_util.py", line 33, in error_check
    return check_first_eval(funs, options, iflag)
  File "/Users/sumneralperin-lea/anaconda3/envs/quantum/lib/python3.6/site-packages/SQImFil/_util.py", line 75, in check_first_eval
    mf, nf = funs.shape
ValueError: not enough values to unpack (expected 2, got 0)
```

This one is somewhat weird; when I look at this file throwing the error on your github, it isn't identical, but when I install either the package as downloaded by pip install or by installing from the git repository, I still get the same file version that is throwing the error.

**Comment by salperinlea** [comment]
Edit:
need to actually force an install of sqimfil 0.3.4 by going into the github download of the package, going to opt/sqimfil, and force installing; pip installation or installing the package itself will install 0.3.3

**Comment by wlav** [comment]
Thanks; I'm working through another couple of known issues and, once I'm through with that, will force exact versions in the top-level setup.py to always pick up the latest in future releases.

**Comment by wlav** [comment]
Regression test has been added.

**Comment by wlav** [comment]
Fixed; path of type '5' (random chosen) was never executed in any of the previous tests and had a bunch of issues.

**Comment by wlav** [comment]
And released on PyPI.
